<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="01HW1740285" name="Loan Department" tests="5" failures="1" timestamp="5 Jun 2023 17:58:51 GMT" time="0.031" errors="0">
  <testcase name="WebhomeLoan" time="0.0" classname="test.Demo3">
    <skipped/>
  </testcase> <!-- WebhomeLoan -->
  <testcase name="Demo" time="0.0" classname="test.Demo1">
    <skipped/>
  </testcase> <!-- Demo -->
  <testcase name="testdemo" time="0.013" classname="test.Demo2"/>
  <testcase name="WebSignOutHCar" time="0.001" classname="test.Demo4"/>
  <testcase name="demo1" time="0.009" classname="test.Demo1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.Demo1.demo1(Demo1.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
</testsuite> <!-- Loan Department -->
